dbMemo "SQL" ="SELECT ExecutiveSummaries.[ShortProjectName], [CleanGPPRData]![Actual Costs]-[Cl"
    "eanGPPRData]![AS Approved Cost Budget] AS DollarsOverBudget, CleanGPPRData.[Actu"
    "al Costs], CleanGPPRData.[AS Approved Cost Budget]\015\012FROM ExecutiveSummarie"
    "s INNER JOIN CleanGPPRData ON ExecutiveSummaries.[ProjectID] = CleanGPPRData.[Pr"
    "oject Number]\015\012WHERE (((ExecutiveSummaries.[ProjectStatus])=\"In Progress\""
    ") And ((CleanGPPRData![Actual Costs]-CleanGPPRData![AS Approved Cost Budget])>0)"
    ")\015\012ORDER BY [CleanGPPRData]![Actual Costs]-[CleanGPPRData]![AS Approved Co"
    "st Budget] DESC;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
dbByte "PublishToWeb" ="1"
        dbText "Name" ="NewExecutiveSummaries.[Short Project Name]"
        dbInteger "ColumnWidth" ="3555"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Approved Costs"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="CleanGPPRData.[Actual Costs]"
        dbInteger "ColumnWidth" ="1545"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="NewExecutiveSummaries.[Project Status]"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="DollarsOverBudget"
        dbInteger "ColumnWidth" ="2175"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="CleanGPPRData.[AS Approved Cost Budget]"
        dbInteger "ColumnWidth" ="1845"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="ExecutiveSummaries.[ShortProjectName]"
        dbLong "AggregateType" ="-1"
    End
End
