dbMemo "SQL" ="SELECT TOP 50 Requests.[Request Date], Requests.[Customer Name], PIDHealthOverBu"
    "dget.[Project PID], PIDHealthOverBudget.[AS Approved Revenue Budget]\015\012FROM"
    " PIDHealthOverBudget INNER JOIN Requests ON PIDHealthOverBudget.[Project PID] = "
    "Requests.[Project ID (PID)]\015\012WHERE (((PIDHealthOverBudget.[Project PID]) I"
    "s Not Null) AND ((PIDHealthOverBudget.[AS Approved Revenue Budget])>150000))\015"
    "\012ORDER BY Requests.[Request Date] DESC;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
dbByte "PublishToWeb" ="1"
        dbText "Name" ="PIDHealthOverBudget.[Project PID]"
        dbInteger "ColumnWidth" ="1860"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="PIDHealthOverBudget.[AS Approved Revenue Budget]"
        dbInteger "ColumnWidth" ="3600"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Requests.[Request Date]"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="[Requests].[Request Date]"
        dbInteger "ColumnWidth" ="2955"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Requests.[Customer Name]"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="[Requests].[Customer Name]"
        dbInteger "ColumnWidth" ="3555"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
End
