dbMemo "SQL" ="SELECT Request.RequestID, Request.ProjectID, Request.CustomerID, Request.Technol"
    "ogyID, Request.ServiceID, Request.StatusID, Assignments.ContactID, Contacts.Full"
    "Name\015\012FROM Contacts RIGHT JOIN (Request LEFT JOIN Assignments ON Request.R"
    "equestID = Assignments.RequestID) ON Contacts.ContactID = Assignments.ContactID\015"
    "\012WHERE (((Request.ProjectID) Like \"*\" & [Forms]![Copy of ProjectSearch]![Pr"
    "ojectID] & \"*\") AND (([Forms]![Copy of ProjectSearch]![CustomerName]) Is Null)"
    " AND (([Forms]![Copy of ProjectSearch]![Technology]) Is Null) AND (([Forms]![Cop"
    "y of ProjectSearch]![ServiceType]) Is Null) AND (([Forms]![Copy of ProjectSearch"
    "]![AssignedResourceID]) Is Null)) OR (((Request.ProjectID) Like \"*\" & [Forms]!"
    "[Copy of ProjectSearch]![ProjectID] & \"*\") AND ((Request.CustomerID)=[Forms]!["
    "Copy of ProjectSearch]![CustomerName]) AND (([Forms]![Copy of ProjectSearch]![Te"
    "chnology]) Is Null) AND (([Forms]![Copy of ProjectSearch]![ServiceType]) Is Null"
    ") AND (([Forms]![Copy of ProjectSearch]![AssignedResourceID]) Is Null)) OR (((Re"
    "quest.ProjectID) Like \"*\" & [Forms]![Copy of ProjectSearch]![ProjectID] & \"*\""
    ") AND ((Request.TechnologyID)=[Forms]![Copy of ProjectSearch]![Technology]) AND "
    "(([Forms]![Copy of ProjectSearch]![CustomerName]) Is Null) AND (([Forms]![Copy o"
    "f ProjectSearch]![ServiceType]) Is Null) AND (([Forms]![Copy of ProjectSearch]!["
    "AssignedResourceID]) Is Null)) OR (((Request.ProjectID) Like \"*\" & [Forms]![Co"
    "py of ProjectSearch]![ProjectID] & \"*\") AND ((Request.CustomerID)=[Forms]![Cop"
    "y of ProjectSearch]![CustomerName]) AND ((Request.TechnologyID)=[Forms]![Copy of"
    " ProjectSearch]![Technology]) AND (([Forms]![Copy of ProjectSearch]![ServiceType"
    "]) Is Null) AND (([Forms]![Copy of ProjectSearch]![AssignedResourceID]) Is Null)"
    ") OR (((Request.ProjectID) Like \"*\" & [Forms]![Copy of ProjectSearch]![Project"
    "ID] & \"*\") AND ((Request.ServiceID)=[Forms]![Copy of ProjectSearch]![ServiceTy"
    "pe]) AND (([Forms]![Copy of ProjectSearch]![CustomerName]) Is Null) AND (([Forms"
    "]![Copy of ProjectSearch]![Technology]) Is Null) AND (([Forms]![Copy of ProjectS"
    "earch]![AssignedResourceID]) Is Null)) OR (((Request.ProjectID) Like \"*\" & [Fo"
    "rms]![Copy of ProjectSearch]![ProjectID] & \"*\") AND ((Request.CustomerID)=[For"
    "ms]![Copy of ProjectSearch]![CustomerName]) AND ((Request.ServiceID)=[Forms]![Co"
    "py of ProjectSearch]![ServiceType]) AND (([Forms]![Copy of ProjectSearch]![Techn"
    "ology]) Is Null) AND (([Forms]![Copy of ProjectSearch]![AssignedResourceID]) Is "
    "Null)) OR (((Request.ProjectID) Like \"*\" & [Forms]![Copy of ProjectSearch]![Pr"
    "ojectID] & \"*\") AND ((Request.TechnologyID)=[Forms]![Copy of ProjectSearch]![T"
    "echnology]) AND ((Request.ServiceID)=[Forms]![Copy of ProjectSearch]![ServiceTyp"
    "e]) AND (([Forms]![Copy of ProjectSearch]![CustomerName]) Is Null) AND (([Forms]"
    "![Copy of ProjectSearch]![AssignedResourceID]) Is Null)) OR (((Request.ProjectID"
    ") Like \"*\" & [Forms]![Copy of ProjectSearch]![ProjectID] & \"*\") AND ((Reques"
    "t.CustomerID)=[Forms]![Copy of ProjectSearch]![CustomerName]) AND ((Request.Tech"
    "nologyID)=[Forms]![Copy of ProjectSearch]![Technology]) AND ((Request.ServiceID)"
    "=[Forms]![Copy of ProjectSearch]![ServiceType]) AND (([Forms]![Copy of ProjectSe"
    "arch]![AssignedResourceID]) Is Null)) OR (((Request.ProjectID) Like \"*\" & [For"
    "ms]![Copy of ProjectSearch]![ProjectID] & \"*\") AND ((Assignments.ContactID)=[F"
    "orms]![Copy of ProjectSearch]![AssignedResourceID]) AND (([Forms]![Copy of Proje"
    "ctSearch]![CustomerName]) Is Null) AND (([Forms]![Copy of ProjectSearch]![Techno"
    "logy]) Is Null) AND (([Forms]![Copy of ProjectSearch]![ServiceType]) Is Null)) O"
    "R (((Request.ProjectID) Like \"*\" & [Forms]![Copy of ProjectSearch]![ProjectID]"
    " & \"*\") AND ((Request.CustomerID)=[Forms]![Copy of ProjectSearch]![CustomerNam"
    "e]) AND ((Assignments.ContactID)=[Forms]![Copy of ProjectSearch]![AssignedResour"
    "ceID]) AND (([Forms]![Copy of ProjectSearch]![Technology]) Is Null) AND (([Forms"
    "]![Copy of ProjectSearch]![ServiceType]) Is Null)) OR (((Request.ProjectID) Like"
    " \"*\" & [Forms]![Copy of ProjectSearch]![ProjectID] & \"*\") AND ((Request.Tech"
    "nologyID)=[Forms]![Copy of ProjectSearch]![Technology]) AND ((Assignments.Contac"
    "tID)=[Forms]![Copy of ProjectSearch]![AssignedResourceID]) AND (([Forms]![Copy o"
    "f ProjectSearch]![CustomerName]) Is Null) AND (([Forms]![Copy of ProjectSearch]!"
    "[ServiceType]) Is Null)) OR (((Request.ProjectID) Like \"*\" & [Forms]![Copy of "
    "ProjectSearch]![ProjectID] & \"*\") AND ((Request.CustomerID)=[Forms]![Copy of P"
    "rojectSearch]![CustomerName]) AND ((Request.TechnologyID)=[Forms]![Copy of Proje"
    "ctSearch]![Technology]) AND ((Assignments.ContactID)=[Forms]![Copy of ProjectSea"
    "rch]![AssignedResourceID]) AND (([Forms]![Copy of ProjectSearch]![ServiceType]) "
    "Is Null)) OR (((Request.ProjectID) Like \"*\" & [Forms]![Copy of ProjectSearch]!"
    "[ProjectID] & \"*\") AND ((Request.ServiceID)=[Forms]![Copy of ProjectSearch]![S"
    "erviceType]) AND ((Assignments.ContactID)=[Forms]![Copy of ProjectSearch]![Assig"
    "nedResourceID]) AND (([Forms]![Copy of ProjectSearch]![CustomerName]) Is Null) A"
    "ND (([Forms]![Copy of ProjectSearch]![Technology]) Is Null)) OR (((Request.Proje"
    "ctID) Like \"*\" & [Forms]![Copy of ProjectSearch]![ProjectID] & \"*\") AND ((Re"
    "quest.CustomerID)=[Forms]![Copy of ProjectSearch]![CustomerName]) AND ((Request."
    "ServiceID)=[Forms]![Copy of ProjectSearch]![ServiceType]) AND ((Assignments.Cont"
    "actID)=[Forms]![Copy of ProjectSearch]![AssignedResourceID]) AND (([Forms]![Copy"
    " of ProjectSearch]![Technology]) Is Null)) OR (((Request.ProjectID) Like \"*\" &"
    " [Forms]![Copy of ProjectSearch]![ProjectID] & \"*\") AND ((Request.TechnologyID"
    ")=[Forms]![Copy of ProjectSearch]![Technology]) AND ((Request.ServiceID)=[Forms]"
    "![Copy of ProjectSearch]![ServiceType]) AND ((Assignments.ContactID)=[Forms]![Co"
    "py of ProjectSearch]![AssignedResourceID]) AND (([Forms]![Copy of ProjectSearch]"
    "![CustomerName]) Is Null)) OR (((Request.ProjectID) Like \"*\" & [Forms]![Copy o"
    "f ProjectSearch]![ProjectID] & \"*\") AND ((Request.CustomerID)=[Forms]![Copy of"
    " ProjectSearch]![CustomerName]) AND ((Request.TechnologyID)=[Forms]![Copy of Pro"
    "jectSearch]![Technology]) AND ((Request.ServiceID)=[Forms]![Copy of ProjectSearc"
    "h]![ServiceType]) AND ((Assignments.ContactID)=[Forms]![Copy of ProjectSearch]!["
    "AssignedResourceID]));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
dbByte "PublishToWeb" ="1"
        dbText "Name" ="Request.RequestID"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Request.ProjectID"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Request.CustomerID"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Request.TechnologyID"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Request.ServiceID"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Request.StatusID"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Request.[RequestID]"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Assignments.ContactID"
        dbLong "AggregateType" ="-1"
    End
        dbText "Name" ="Contacts.FullName"
        dbLong "AggregateType" ="-1"
    End
End
