Version =20
VersionRequired =20
PublishOption =1
    LayoutForPrint = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    DateGrouping =1
    GrpKeepTogether =1
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =7230
    DatasheetFontHeight =11
    ItemSuffix =42
    Right =21570
    Bottom =12345
    DatasheetGridlinesColor =16316664
        0x9ee81ce02a3de440
    End
    RecordSource ="_TOP10ExSummaryOverBudgetProjectsByPercentOverage"
    DatasheetFontName ="Calibri"
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    FilterOnLoad =0
    FitToPage =1
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            FontSize =11
            ForeColor =6050636
            FontName ="Calibri"
            GridlineColor =-2147483609
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
            BorderThemeColorIndex =0
        End
            OldBorderStyle =0
            BorderLineStyle =0
            SizeMode =3
            PictureAlignment =2
            BorderColor =16777215
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            GridlineColor =-2147483609
            ForeThemeColorIndex =0
            ForeTint =75.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            GridlineColor =-2147483609
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            GridlineColor =-2147483609
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            AddColon = NotDefault
            SizeMode =3
            BorderLineStyle =0
            LabelX =-1800
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            GridlineColor =-2147483609
            ShowDatePicker =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            GridlineColor =-2147483609
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            AddColon = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            GridlineColor =-2147483609
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            GridlineColor =-2147483609
            ForeThemeColorIndex =0
            ForeTint =75.0
            UseTheme =1
            Shape =2
            Bevel =1
            BackColor =-1
            BackThemeColorIndex =4
            BackTint =60.0
            OldBorderStyle =0
            BorderLineStyle =0
            BorderColor =-1
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverColor =0
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedColor =0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeColor =0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeColor =0
            PressedForeThemeColorIndex =1
        End
            FontSize =11
            FontName ="Calibri"
            GridlineColor =-2147483609
            ThemeFontIndex =0
            UseTheme =1
            Shape =3
            BackThemeColorIndex =1
            BackShade =85.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =2
            BorderTint =60.0
            HoverThemeColorIndex =1
            PressedThemeColorIndex =1
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            GridlineColor =-2147483609
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BackStyle =0
            BorderLineStyle =0
            PictureSizeMode =3
            Width =4800
            Height =3840
            GridlineColor =-2147483609
            LabelX =-1800
            AddColon =0
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            Height =240
            GridlineColor =-2147483609
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderWidth =1
            BorderLineStyle =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            GridlineColor =-2147483609
        End
            ForeColor =-2
            GridlineColor =-2147483609
            HoverColor =-2
            HoverThemeColorIndex =2
            HoverTint =20.0
            PressedColor =-2
            PressedThemeColorIndex =2
            PressedTint =60.0
            HoverForeColor =-2
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeColor =-2
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            BackColor =15790320
            BackThemeColorIndex =1
            OldBorderStyle =0
            BorderLineStyle =0
            BorderThemeColorIndex =3
            BorderShade =90.0
            ThemeFontIndex =1
            FontName ="Calibri"
            FontWeight =400
            FontSize =11
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            KeepTogether = NotDefault
            CanGrow = NotDefault
            CanShrink = NotDefault
            Height =1020
            BackColor =967423
            Name ="ReportHeader"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
                    TextAlign =1
                    Left =300
                    Top =60
                    Width =3135
                    Height =315
                    FontWeight =700
                    ForeColor =0
                    Name ="Auto_Header0"
                    Caption ="Top 10 Over budget projects"
                    GroupTable =2
                    HorizontalAnchor =2
                    LayoutCachedLeft =300
                    LayoutCachedTop =60
                    LayoutCachedWidth =3435
                    LayoutCachedHeight =375
                    RowEnd =1
                    LayoutGroup =2
                    BorderThemeColorIndex =2
                    BorderTint =100.0
                    ForeTint =100.0
                    GroupTable =2
                End
                    BackStyle =1
                    Left =60
                    Top =420
                    Width =1515
                    Height =540
                    FontSize =10
                    FontWeight =700
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BackColor =967423
                    BorderColor =8355711
                    ForeColor =0
                    Name ="Label0"
                    Caption ="Short Project Name"
                    GroupTable =3
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =60
                    LayoutCachedTop =420
                    LayoutCachedWidth =1575
                    LayoutCachedHeight =960
                    LayoutGroup =3
                    BackThemeColorIndex =-1
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =3
                End
                    BackStyle =1
                    Left =4815
                    Top =420
                    Width =1500
                    Height =540
                    FontSize =10
                    FontWeight =700
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BackColor =967423
                    BorderColor =8355711
                    ForeColor =0
                    Name ="Label1"
                    Caption ="$ Over Budget"
                    GroupTable =3
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =4815
                    LayoutCachedTop =420
                    LayoutCachedWidth =6315
                    LayoutCachedHeight =960
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =3
                    BackThemeColorIndex =-1
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =3
                End
                    BackStyle =1
                    Left =6375
                    Top =420
                    Width =825
                    Height =540
                    FontSize =10
                    FontWeight =700
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BackColor =967423
                    BorderColor =8355711
                    ForeColor =0
                    Name ="Label2"
                    Caption ="% of Total"
                    GroupTable =3
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =6375
                    LayoutCachedTop =420
                    LayoutCachedWidth =7200
                    LayoutCachedHeight =960
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =3
                    BackThemeColorIndex =-1
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =3
                End
                    BackStyle =1
                    Left =1635
                    Top =420
                    Width =1500
                    Height =540
                    FontSize =10
                    FontWeight =700
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BackColor =967423
                    BorderColor =8355711
                    ForeColor =0
                    Name ="Label23"
                    Caption ="Approved Cost"
                    GroupTable =3
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =1635
                    LayoutCachedTop =420
                    LayoutCachedWidth =3135
                    LayoutCachedHeight =960
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =3
                    BackThemeColorIndex =-1
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =3
                End
                    BackStyle =1
                    Left =3195
                    Top =420
                    Width =1560
                    Height =540
                    FontSize =10
                    FontWeight =700
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BackColor =967423
                    BorderColor =8355711
                    ForeColor =0
                    Name ="Label24"
                    Caption ="Costs to Date"
                    GroupTable =3
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =3195
                    LayoutCachedTop =420
                    LayoutCachedWidth =4755
                    LayoutCachedHeight =960
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =3
                    BackThemeColorIndex =-1
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =3
                End
            End
        End
            Height =0
            BackColor =967423
            Name ="PageHeaderSection"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
        End
            KeepTogether = NotDefault
            CanGrow = NotDefault
            CanShrink = NotDefault
            Height =397
            Name ="Detail"
            AutoHeight =1
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
                    CanGrow = NotDefault
                    CanShrink = NotDefault
                    OldBorderStyle =0
                    IMESentenceMode =3
                    Left =60
                    Top =30
                    Width =1515
                    Height =345
                    ColumnWidth =3705
                    FontSize =10
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Short Project Name"
                    ControlSource ="ShortProjectName"
                    EventProcPrefix ="Short_Project_Name"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =60
                    LayoutCachedTop =30
                    LayoutCachedWidth =1575
                    LayoutCachedHeight =375
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    OldBorderStyle =0
                    TextAlign =3
                    IMESentenceMode =3
                    Left =4815
                    Top =30
                    Width =1500
                    Height =345
                    ColumnWidth =2175
                    FontSize =10
                    TabIndex =3
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="DollarsOverBudget"
                    ControlSource ="Dollars Over Budget"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =4815
                    LayoutCachedTop =30
                    LayoutCachedWidth =6315
                    LayoutCachedHeight =375
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    CanGrow = NotDefault
                    CanShrink = NotDefault
                    OldBorderStyle =0
                    TextAlign =3
                    IMESentenceMode =3
                    Left =6375
                    Top =30
                    Width =825
                    Height =345
                    FontSize =10
                    TabIndex =4
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="% of Total Over Budget"
                    ControlSource ="% of Total Over Budget"
                    EventProcPrefix ="Ctl__of_Total_Over_Budget"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =6375
                    LayoutCachedTop =30
                    LayoutCachedWidth =7200
                    LayoutCachedHeight =375
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    OldBorderStyle =0
                    TextAlign =3
                    IMESentenceMode =3
                    Left =1635
                    Top =30
                    Width =1500
                    Height =345
                    ColumnWidth =1785
                    FontSize =10
                    TabIndex =1
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Approved Cost"
                    ControlSource ="Approved Cost"
                    Format ="$#,##0.00;[Red]($#,##0.00)"
                    EventProcPrefix ="Approved_Cost"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =1635
                    LayoutCachedTop =30
                    LayoutCachedWidth =3135
                    LayoutCachedHeight =375
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    OldBorderStyle =0
                    TextAlign =3
                    IMESentenceMode =3
                    Left =3195
                    Top =30
                    Width =1560
                    Height =345
                    ColumnWidth =1545
                    FontSize =10
                    TabIndex =2
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Costs to Date"
                    ControlSource ="Costs to Date"
                    Format ="$#,##0.00;[Red]($#,##0.00)"
                    EventProcPrefix ="Costs_to_Date"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =3195
                    LayoutCachedTop =30
                    LayoutCachedWidth =4755
                    LayoutCachedHeight =375
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
            End
        End
            Height =0
            Name ="PageFooterSection"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
            KeepTogether = NotDefault
            CanGrow = NotDefault
            CanShrink = NotDefault
            Height =0
            Name ="ReportFooter"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
