Version =20
VersionRequired =20
PublishOption =1
    LayoutForPrint = NotDefault
    AllowDeletions = NotDefault
    DividingLines = NotDefault
    AllowAdditions = NotDefault
    AllowEdits = NotDefault
    AllowDesignChanges = NotDefault
    DateGrouping =1
    GrpKeepTogether =1
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =11385
    DatasheetFontHeight =11
    ItemSuffix =32
    Left =300
    Top =5490
    Right =11685
    Bottom =9000
    DatasheetGridlinesColor =14806254
        0x1aa6f1155736e440
    End
    RecordSource ="AllCommentsByRequestID"
    DatasheetFontName ="Calibri"
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    FilterOnLoad =0
    FitToPage =1
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            FontSize =11
            ForeColor =6050636
            FontName ="Calibri"
            GridlineColor =-2147483609
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
            BorderThemeColorIndex =0
        End
            OldBorderStyle =0
            BorderLineStyle =0
            SizeMode =3
            PictureAlignment =2
            BorderColor =16777215
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            GridlineColor =-2147483609
            ForeThemeColorIndex =0
            ForeTint =75.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            GridlineColor =-2147483609
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            GridlineColor =-2147483609
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            AddColon = NotDefault
            SizeMode =3
            BorderLineStyle =0
            LabelX =-1800
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            GridlineColor =-2147483609
            ShowDatePicker =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            GridlineColor =-2147483609
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            AddColon = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            GridlineColor =-2147483609
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
        End
            BorderLineStyle =0
            GridlineColor =-2147483609
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            GridlineColor =-2147483609
            ForeThemeColorIndex =0
            ForeTint =75.0
            UseTheme =1
            Shape =2
            Bevel =1
            BackColor =-1
            BackThemeColorIndex =4
            BackTint =60.0
            OldBorderStyle =0
            BorderLineStyle =0
            BorderColor =-1
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverColor =0
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedColor =0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeColor =0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeColor =0
            PressedForeThemeColorIndex =1
        End
            FontSize =11
            FontName ="Calibri"
            GridlineColor =-2147483609
            ThemeFontIndex =0
            UseTheme =1
            Shape =3
            BackThemeColorIndex =1
            BackShade =85.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =2
            BorderTint =60.0
            HoverThemeColorIndex =1
            PressedThemeColorIndex =1
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            GridlineColor =-2147483609
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BackStyle =0
            BorderLineStyle =0
            PictureSizeMode =3
            Width =4800
            Height =3840
            GridlineColor =-2147483609
            LabelX =-1800
            AddColon =0
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            Height =240
            GridlineColor =-2147483609
        End
            OldBorderStyle =1
            GridlineColor =-2147483609
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
        End
            BorderWidth =1
            BorderLineStyle =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            GridlineColor =-2147483609
        End
            ForeColor =-2
            GridlineColor =-2147483609
            HoverColor =-2
            HoverThemeColorIndex =2
            HoverTint =20.0
            PressedColor =-2
            PressedThemeColorIndex =2
            PressedTint =60.0
            HoverForeColor =-2
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeColor =-2
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            BackColor =15790320
            BackThemeColorIndex =1
            OldBorderStyle =0
            BorderLineStyle =0
            BorderThemeColorIndex =3
            BorderShade =90.0
            ThemeFontIndex =1
            FontName ="Calibri"
            FontWeight =400
            FontSize =11
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            SortOrder = NotDefault
            ControlSource ="DateTime"
        End
            KeepTogether = NotDefault
            CanGrow = NotDefault
            CanShrink = NotDefault
            Height =0
            BackColor =15849926
            Name ="ReportHeader"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =2
            BackTint =20.0
        End
            Height =449
            Name ="PageHeaderSection"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    Visible = NotDefault
                    Left =60
                    Top =60
                    Width =195
                    Height =359
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =8355711
                    ForeColor =8355711
                    Name ="Label0"
                    Caption ="RequestID"
                    GroupTable =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =60
                    LayoutCachedTop =60
                    LayoutCachedWidth =255
                    LayoutCachedHeight =419
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    Left =315
                    Top =60
                    Width =1440
                    Height =359
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =8355711
                    ForeColor =8355711
                    Name ="Label1"
                    Caption ="DateTime"
                    GroupTable =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =315
                    LayoutCachedTop =60
                    LayoutCachedWidth =1755
                    LayoutCachedHeight =419
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    Left =1815
                    Top =60
                    Width =9480
                    Height =359
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =8355711
                    ForeColor =8355711
                    Name ="Label2"
                    Caption ="PMO Notes"
                    GroupTable =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =1815
                    LayoutCachedTop =60
                    LayoutCachedWidth =11295
                    LayoutCachedHeight =419
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    Visible = NotDefault
                    Left =11355
                    Top =60
                    Width =0
                    Height =359
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =8355711
                    ForeColor =8355711
                    Name ="Label25"
                    Caption ="RequestID"
                    GroupTable =1
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =11355
                    LayoutCachedTop =60
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =419
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
            End
        End
            KeepTogether = NotDefault
            CanGrow = NotDefault
            CanShrink = NotDefault
            Height =412
            Name ="Detail"
            AutoHeight =1
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    Visible = NotDefault
                    OldBorderStyle =0
                    IMESentenceMode =3
                    Left =60
                    Top =30
                    Width =195
                    Height =360
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="RequestID"
                    ControlSource ="RequestID"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =60
                    LayoutCachedTop =30
                    LayoutCachedWidth =255
                    LayoutCachedHeight =390
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    OldBorderStyle =0
                    IMESentenceMode =3
                    Left =315
                    Top =30
                    Height =360
                    ColumnWidth =1695
                    TabIndex =1
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Date/Time"
                    ControlSource ="DateTime"
                    Format ="Short Date"
                    EventProcPrefix ="Date_Time"
                    GroupTable =1
                    GridlineColor =10921638
                    ShowDatePicker =1

                    LayoutCachedLeft =315
                    LayoutCachedTop =30
                    LayoutCachedWidth =1755
                    LayoutCachedHeight =390
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    CanGrow = NotDefault
                    CanShrink = NotDefault
                    EnterKeyBehavior = NotDefault
                    OldBorderStyle =0
                    IMESentenceMode =3
                    Left =1815
                    Top =30
                    Width =9480
                    Height =360
                    ColumnWidth =2235
                    TabIndex =2
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="PMO Notes"
                    ControlSource ="PMONotes"
                    EventProcPrefix ="PMO_Notes"
                    GroupTable =1
                    GridlineColor =10921638
                    TextFormat =1

                    LayoutCachedLeft =1815
                    LayoutCachedTop =30
                    LayoutCachedWidth =11295
                    LayoutCachedHeight =390
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
                    Visible = NotDefault
                    OldBorderStyle =0
                    IMESentenceMode =3
                    Left =11355
                    Top =30
                    Width =0
                    Height =360
                    TabIndex =3
                    LeftMargin =44
                    TopMargin =22
                    RightMargin =44
                    BottomMargin =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Text24"
                    ControlSource ="RequestID"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =11355
                    LayoutCachedTop =30
                    LayoutCachedWidth =11355
                    LayoutCachedHeight =390
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =1
                End
            End
        End
            Height =0
            Name ="PageFooterSection"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
            KeepTogether = NotDefault
            CanGrow = NotDefault
            CanShrink = NotDefault
            Height =0
            Name ="ReportFooter"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
