Version =20
VersionRequired =20
PublishOption =1
    RecordSelectors = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =8700
    DatasheetFontHeight =11
    ItemSuffix =135
    Right =14910
    Bottom =12105
    DatasheetGridlinesColor =16316664
        0xc13923c21240e440
    End
    RecordSource ="SELECT D10Checklist.ChecklistID, D10Checklist.ReqsSent, D10Checklist.CustomerTem"
        "plateSent, D10Checklist.AccountTeamReview, D10Checklist.WorkshopLocation, D10Che"
        "cklist.Lunch, D10Checklist.ConferenceRoom, D10Checklist.Whiteboards, D10Checklis"
        "t.FlipChart, D10Checklist.Projector, D10Checklist.CustomerAttendees, D10Checklis"
        "t.TemplateCompleted, D10Checklist.DateConfirmed, D10Checklist.RequestID FROM D10"
        "Checklist; "
    DatasheetFontName ="Calibri"
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            SpecialEffect =3
            BorderLineStyle =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            SizeMode =3
            SpecialEffect =2
            BorderLineStyle =0
            LabelX =-1800
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =240
            GridlineColor =12632256
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            DisplayWhen =1
            Height =585
            Name ="PageHeaderSection"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    Visible = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =1395
                    Top =120
                    Height =315
                    ColumnOrder =0
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="ID"
                    ControlSource ="ChecklistID"
                    GroupTable =6
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =1395
                    LayoutCachedTop =120
                    LayoutCachedWidth =2835
                    LayoutCachedHeight =435
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =4
                    GroupTable =6
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =120
                            Width =1035
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label119"
                            Caption ="ID"
                            GroupTable =6
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =120
                            LayoutCachedWidth =1335
                            LayoutCachedHeight =435
                            LayoutGroup =4
                            GroupTable =6
                        End
                    End
                End
                    Visible = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =3990
                    Top =120
                    Height =315
                    ColumnOrder =1
                    TabIndex =1
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="RequestID"
                    ControlSource ="RequestID"
                    GroupTable =6
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =3990
                    LayoutCachedTop =120
                    LayoutCachedWidth =5430
                    LayoutCachedHeight =435
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =4
                    GroupTable =6
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =2895
                            Top =120
                            Width =1035
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label120"
                            Caption ="RequestID"
                            GroupTable =6
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =2895
                            LayoutCachedTop =120
                            LayoutCachedWidth =3930
                            LayoutCachedHeight =435
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =4
                            GroupTable =6
                        End
                    End
                End
            End
        End
            Height =4020
            Name ="Detail"
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    BorderWidth =3
                    OverlapFlags =93
                    Left =360
                    Top =300
                    Width =3900
                    Height =1800
                    BackColor =15921906
                    BorderColor =10921638
                    Name ="Internalbox"
                    GridlineColor =10921638

                    LayoutCachedLeft =360
                    LayoutCachedTop =300
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =2100
                    BackShade =95.0
                            BackStyle =1
                            OverlapFlags =215
                            Left =480
                            Top =180
                            Width =885
                            Height =315
                            FontWeight =700
                            BorderColor =14277081
                            ForeColor =7303023
                            Name ="InternalLabel"
                            Caption ="Internal"
                            GridlineColor =10921638
                            LayoutCachedLeft =480
                            LayoutCachedTop =180
                            LayoutCachedWidth =1365
                            LayoutCachedHeight =495
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            BorderShade =85.0
                            ForeThemeColorIndex =4
                            ForeTint =100.0
                            ForeShade =50.0
                        End
                    End
                End
                    OverlapFlags =215
                    Left =2610
                    Top =600
                    Width =1440
                    Height =315
                    TabIndex =2
                    BorderColor =10921638
                    Name ="Workshop Reqs Sent"
                    ControlSource ="ReqsSent"
                    StatusBarText ="Has the prep documentation been sent?"
                    EventProcPrefix ="Workshop_Reqs_Sent"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =2610
                    LayoutCachedTop =600
                    LayoutCachedWidth =4050
                    LayoutCachedHeight =915
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =215
                            TextAlign =1
                            Left =480
                            Top =600
                            Width =2070
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label3"
                            Caption ="Requirements Sent"
                            GroupTable =1
                            GridlineColor =10921638
                            LayoutCachedLeft =480
                            LayoutCachedTop =600
                            LayoutCachedWidth =2550
                            LayoutCachedHeight =915
                            LayoutGroup =1
                            ForeTint =65.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =215
                    Left =2610
                    Top =975
                    Width =1440
                    Height =315
                    TabIndex =3
                    BorderColor =10921638
                    Name ="Template Sent"
                    ControlSource ="CustomerTemplateSent"
                    EventProcPrefix ="Template_Sent"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =2610
                    LayoutCachedTop =975
                    LayoutCachedWidth =4050
                    LayoutCachedHeight =1290
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =215
                            TextAlign =1
                            Left =480
                            Top =975
                            Width =2070
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label4"
                            Caption ="Template Sent"
                            GroupTable =1
                            GridlineColor =10921638
                            LayoutCachedLeft =480
                            LayoutCachedTop =975
                            LayoutCachedWidth =2550
                            LayoutCachedHeight =1290
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =1
                            ForeTint =65.0
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =215
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2610
                    Top =1350
                    Height =315
                    TabIndex =4
                    BorderColor =10921638
                    ForeColor =5855577
                    Name ="Account Team review"
                    ControlSource ="AccountTeamReview"
                    EventProcPrefix ="Account_Team_review"
                    GroupTable =1
                    GridlineColor =10921638

                    LayoutCachedLeft =2610
                    LayoutCachedTop =1350
                    LayoutCachedWidth =4050
                    LayoutCachedHeight =1665
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeTint =65.0
                    GroupTable =1
                            OverlapFlags =215
                            TextAlign =1
                            Left =480
                            Top =1350
                            Width =2070
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label5"
                            Caption ="Acct. Team Review"
                            GroupTable =1
                            GridlineColor =10921638
                            LayoutCachedLeft =480
                            LayoutCachedTop =1350
                            LayoutCachedWidth =2550
                            LayoutCachedHeight =1665
                            RowStart =2
                            RowEnd =2
                            LayoutGroup =1
                            ForeTint =65.0
                            GroupTable =1
                        End
                    End
                End
                    BorderWidth =3
                    OverlapFlags =93
                    Left =4440
                    Top =300
                    Width =4080
                    Height =1800
                    TabIndex =1
                    BackColor =15921906
                    BorderColor =10921638
                    Name ="Frame12"
                    GridlineColor =10921638

                    LayoutCachedLeft =4440
                    LayoutCachedTop =300
                    LayoutCachedWidth =8520
                    LayoutCachedHeight =2100
                    BackShade =95.0
                            BackStyle =1
                            OverlapFlags =215
                            Left =4560
                            Top =180
                            Width =1005
                            Height =315
                            FontWeight =700
                            BorderColor =14277081
                            ForeColor =7303023
                            Name ="Label13"
                            Caption ="Location"
                            GridlineColor =10921638
                            LayoutCachedLeft =4560
                            LayoutCachedTop =180
                            LayoutCachedWidth =5565
                            LayoutCachedHeight =495
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            BorderShade =85.0
                            ForeThemeColorIndex =4
                            ForeTint =100.0
                            ForeShade =50.0
                        End
                    End
                End
                    OverlapFlags =215
                    TextAlign =1
                    IMESentenceMode =3
                    Left =5940
                    Top =540
                    Width =2280
                    Height =315
                    TabIndex =5
                    BorderColor =10921638
                    ForeColor =5855577
                    Name ="Offsite Location"
                    ControlSource ="WorkshopLocation"
                    EventProcPrefix ="Offsite_Location"
                    GroupTable =2
                    GridlineColor =10921638

                    LayoutCachedLeft =5940
                    LayoutCachedTop =540
                    LayoutCachedWidth =8220
                    LayoutCachedHeight =855
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =2
                    ForeTint =65.0
                    GroupTable =2
                            OverlapFlags =215
                            TextAlign =1
                            Left =4500
                            Top =540
                            Width =1380
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label14"
                            Caption ="Address"
                            GroupTable =2
                            GridlineColor =10921638
                            LayoutCachedLeft =4500
                            LayoutCachedTop =540
                            LayoutCachedWidth =5880
                            LayoutCachedHeight =855
                            LayoutGroup =2
                            ForeTint =65.0
                            GroupTable =2
                        End
                    End
                End
                    OverlapFlags =215
                    TextAlign =1
                    IMESentenceMode =3
                    Left =5940
                    Top =915
                    Width =2280
                    Height =315
                    TabIndex =6
                    BorderColor =10921638
                    ForeColor =5855577
                    Name ="Conference Room"
                    ControlSource ="ConferenceRoom"
                    EventProcPrefix ="Conference_Room"
                    GroupTable =2
                    GridlineColor =10921638

                    LayoutCachedLeft =5940
                    LayoutCachedTop =915
                    LayoutCachedWidth =8220
                    LayoutCachedHeight =1230
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =2
                    ForeTint =65.0
                    GroupTable =2
                            OverlapFlags =215
                            TextAlign =1
                            Left =4500
                            Top =915
                            Width =1380
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label15"
                            Caption ="Room Name"
                            GroupTable =2
                            GridlineColor =10921638
                            LayoutCachedLeft =4500
                            LayoutCachedTop =915
                            LayoutCachedWidth =5880
                            LayoutCachedHeight =1230
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =2
                            ForeTint =65.0
                            GroupTable =2
                        End
                    End
                End
                    OverlapFlags =215
                    Left =6000
                    Top =1320
                    Width =240
                    Height =315
                    TabIndex =7
                    BorderColor =10921638
                    Name ="Lunch"
                    ControlSource ="Lunch"
                    GroupTable =4
                    LeftPadding =90
                    RightPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =6000
                    LayoutCachedTop =1320
                    LayoutCachedWidth =6240
                    LayoutCachedHeight =1635
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =3
                    GroupTable =4
                            OverlapFlags =215
                            TextAlign =1
                            Left =4500
                            Top =1320
                            Width =1380
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label20"
                            Caption ="Lunch"
                            GroupTable =4
                            GridlineColor =10921638
                            LayoutCachedLeft =4500
                            LayoutCachedTop =1320
                            LayoutCachedWidth =5880
                            LayoutCachedHeight =1635
                            LayoutGroup =3
                            ForeTint =65.0
                            GroupTable =4
                        End
                    End
                End
                    OverlapFlags =215
                    Left =7920
                    Top =1320
                    Width =375
                    Height =315
                    TabIndex =8
                    BorderColor =10921638
                    Name ="White boards"
                    ControlSource ="Whiteboards"
                    EventProcPrefix ="White_boards"
                    GroupTable =4
                    LeftPadding =90
                    RightPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =7920
                    LayoutCachedTop =1320
                    LayoutCachedWidth =8295
                    LayoutCachedHeight =1635
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =3
                    GroupTable =4
                            OverlapFlags =215
                            TextAlign =1
                            Left =6420
                            Top =1320
                            Width =1320
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label21"
                            Caption ="White boards"
                            GroupTable =4
                            LeftPadding =90
                            RightPadding =90
                            GridlineColor =10921638
                            LayoutCachedLeft =6420
                            LayoutCachedTop =1320
                            LayoutCachedWidth =7740
                            LayoutCachedHeight =1635
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =3
                            ForeTint =65.0
                            GroupTable =4
                        End
                    End
                End
                    OverlapFlags =215
                    Left =7920
                    Top =1755
                    Width =375
                    Height =300
                    TabIndex =10
                    BorderColor =10921638
                    Name ="Flip Chart"
                    ControlSource ="FlipChart"
                    EventProcPrefix ="Flip_Chart"
                    GroupTable =4
                    LeftPadding =90
                    TopPadding =90
                    RightPadding =90
                    BottomPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =7920
                    LayoutCachedTop =1755
                    LayoutCachedWidth =8295
                    LayoutCachedHeight =2055
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =3
                    GroupTable =4
                            OverlapFlags =215
                            TextAlign =1
                            Left =6420
                            Top =1755
                            Width =1320
                            Height =300
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label22"
                            Caption ="Flip Chart"
                            GroupTable =4
                            LeftPadding =90
                            TopPadding =90
                            RightPadding =90
                            BottomPadding =90
                            GridlineColor =10921638
                            LayoutCachedLeft =6420
                            LayoutCachedTop =1755
                            LayoutCachedWidth =7740
                            LayoutCachedHeight =2055
                            RowStart =1
                            RowEnd =1
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =3
                            ForeTint =65.0
                            GroupTable =4
                        End
                    End
                End
                    OverlapFlags =215
                    Left =6000
                    Top =1755
                    Width =240
                    Height =300
                    TabIndex =9
                    BorderColor =10921638
                    Name ="Projector"
                    ControlSource ="Projector"
                    GroupTable =4
                    LeftPadding =90
                    TopPadding =90
                    RightPadding =90
                    BottomPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =6000
                    LayoutCachedTop =1755
                    LayoutCachedWidth =6240
                    LayoutCachedHeight =2055
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =3
                    GroupTable =4
                            OverlapFlags =215
                            TextAlign =1
                            Left =4500
                            Top =1755
                            Width =1380
                            Height =300
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label23"
                            Caption ="Projector"
                            GroupTable =4
                            TopPadding =90
                            BottomPadding =90
                            GridlineColor =10921638
                            LayoutCachedLeft =4500
                            LayoutCachedTop =1755
                            LayoutCachedWidth =5880
                            LayoutCachedHeight =2055
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =3
                            ForeTint =65.0
                            GroupTable =4
                        End
                    End
                End
                    BorderWidth =3
                    OverlapFlags =93
                    Left =360
                    Top =2280
                    Width =8160
                    Height =1560
                    TabIndex =11
                    BackColor =15921906
                    BorderColor =10921638
                    Name ="Frame72"
                    GridlineColor =10921638

                    LayoutCachedLeft =360
                    LayoutCachedTop =2280
                    LayoutCachedWidth =8520
                    LayoutCachedHeight =3840
                    BackShade =95.0
                            BackStyle =1
                            OverlapFlags =215
                            Left =480
                            Top =2160
                            Width =1110
                            Height =315
                            FontWeight =700
                            BorderColor =14277081
                            ForeColor =7303023
                            Name ="Label73"
                            Caption ="Customer"
                            GridlineColor =10921638
                            LayoutCachedLeft =480
                            LayoutCachedTop =2160
                            LayoutCachedWidth =1590
                            LayoutCachedHeight =2475
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            BorderShade =85.0
                            ForeThemeColorIndex =4
                            ForeTint =100.0
                            ForeShade =50.0
                        End
                    End
                End
                    OverlapFlags =215
                    TextAlign =1
                    IMESentenceMode =3
                    Left =1740
                    Top =2580
                    Width =6600
                    Height =660
                    TabIndex =12
                    BorderColor =10921638
                    ForeColor =5855577
                    Name ="Customer Attendees"
                    ControlSource ="CustomerAttendees"
                    StatusBarText ="Names and Roles of who will attend"
                    EventProcPrefix ="Customer_Attendees"
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =1740
                    LayoutCachedTop =2580
                    LayoutCachedWidth =8340
                    LayoutCachedHeight =3240
                    ColumnStart =1
                    ColumnEnd =1
                    ForeTint =65.0
                            OverlapFlags =215
                            TextAlign =1
                            Left =480
                            Top =2580
                            Width =1140
                            Height =660
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label75"
                            Caption ="Customer Attendees"
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =480
                            LayoutCachedTop =2580
                            LayoutCachedWidth =1620
                            LayoutCachedHeight =3240
                            ForeTint =65.0
                        End
                    End
                End
                    OverlapFlags =215
                    Left =8100
                    Top =3435
                    Width =225
                    Height =315
                    TabIndex =14
                    BorderColor =10921638
                    Name ="Pre-workshop Template complete"
                    ControlSource ="TemplateCompleted"
                    EventProcPrefix ="Pre_workshop_Template_complete"
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =8100
                    LayoutCachedTop =3435
                    LayoutCachedWidth =8325
                    LayoutCachedHeight =3750
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                            OverlapFlags =215
                            TextAlign =1
                            Left =6060
                            Top =3420
                            Width =1980
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label76"
                            Caption ="Template Complete"
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =6060
                            LayoutCachedTop =3420
                            LayoutCachedWidth =8040
                            LayoutCachedHeight =3735
                            RowStart =1
                            RowEnd =1
                            ForeTint =65.0
                        End
                    End
                End
                    OverlapFlags =215
                    Left =5700
                    Top =3435
                    Width =225
                    Height =315
                    TabIndex =13
                    BorderColor =10921638
                    Name ="Confirmed Full 1 Day"
                    ControlSource ="DateConfirmed"
                    EventProcPrefix ="Confirmed_Full_1_Day"
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =5700
                    LayoutCachedTop =3435
                    LayoutCachedWidth =5925
                    LayoutCachedHeight =3750
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                            OverlapFlags =215
                            TextAlign =1
                            Left =3660
                            Top =3420
                            Width =1980
                            Height =315
                            BorderColor =8355711
                            ForeColor =5855577
                            Name ="Label77"
                            Caption ="Confirmed Full Day"
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =3660
                            LayoutCachedTop =3420
                            LayoutCachedWidth =5640
                            LayoutCachedHeight =3735
                            RowStart =2
                            RowEnd =2
                            ForeTint =65.0
                        End
                    End
                End
            End
        End
            DisplayWhen =1
            Height =0
            Name ="PageFooterSection"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
