Version =20
VersionRequired =20
PublishOption =1
    DividingLines = NotDefault
    FilterOn = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =2
    ViewsAllowed =2
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =4440
    DatasheetFontHeight =11
    ItemSuffix =35
    Left =3150
    Top =2070
    Right =14535
    Bottom =6570
    DatasheetGridlinesColor =16316664
        0x10ff126d913be440
    End
    RecordSource ="Assignments"
    DatasheetFontName ="Calibri"
    AllowFormView =0
    AllowPivotTableView =0
    AllowPivotChartView =0
    AllowPivotChartView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =240
            GridlineColor =12632256
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =4545
            Name ="Detail"
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    ColumnHidden = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2310
                    Top =120
                    Width =1950
                    Height =315
                    ColumnWidth =735
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="ID"
                    ControlSource ="AssignmentID"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2310
                    LayoutCachedTop =120
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =435
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =120
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label0"
                            Caption ="Assignment ID"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =120
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =435
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    ColumnHidden = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMEMode =2
                    IMESentenceMode =3
                    Left =2310
                    Top =615
                    Width =1950
                    Height =315
                    ColumnWidth =1635
                    TabIndex =3
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Request Date"
                    ControlSource ="DateAssigned"
                    Format ="Medium Date"
                    EventProcPrefix ="Request_Date"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2310
                    LayoutCachedTop =615
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =930
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =615
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label1"
                            Caption ="Assignment Date:"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =615
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =930
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMEMode =2
                    IMESentenceMode =3
                    Left =2310
                    Top =2100
                    Width =1950
                    Height =315
                    TabIndex =4
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Start Date"
                    ControlSource ="StartDate"
                    Format ="Medium Date"
                    EventProcPrefix ="Start_Date"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2310
                    LayoutCachedTop =2100
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =2415
                    RowStart =4
                    RowEnd =4
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =2100
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label3"
                            Caption ="Start Date"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =2100
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =2415
                            RowStart =4
                            RowEnd =4
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2310
                    Top =2595
                    Width =1950
                    Height =315
                    TabIndex =5
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="End Date"
                    ControlSource ="Enddate"
                    EventProcPrefix ="End_Date"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2310
                    LayoutCachedTop =2595
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =2910
                    RowStart =5
                    RowEnd =5
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =2595
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label4"
                            Caption ="End Date"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =2595
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =2910
                            RowStart =5
                            RowEnd =5
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    LimitToList = NotDefault
                    ColumnHidden = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    ColumnCount =2
                    Left =2310
                    Top =3090
                    Width =1950
                    Height =315
                    ColumnWidth =1650
                    TabIndex =6
                    BorderColor =10921638
                    Name ="DCPM Assigned"
                    ControlSource ="ContactID"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT [ID], [Contact Name] FROM [Contacts Extended] ORDER BY [Contact Name]; "
                    ColumnWidths ="0;1440"
                    EventProcPrefix ="DCPM_Assigned"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638
                    ListItemsEditForm ="ContactDetails"

                    LayoutCachedLeft =2310
                    LayoutCachedTop =3090
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =3405
                    RowStart =6
                    RowEnd =6
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =3090
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label5"
                            Caption ="DCPM Assigned"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =3090
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =3405
                            RowStart =6
                            RowEnd =6
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    LimitToList = NotDefault
                    Locked = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    ColumnCount =2
                    Left =2310
                    Top =4080
                    Width =1950
                    Height =315
                    ColumnWidth =2625
                    TabIndex =8
                    BorderColor =10921638
                    ColumnInfo ="\"\";\"\";\"\";\"\";\"10\";\"100\""
                    Name ="DCPM Project Status"
                    ControlSource ="RequestID"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT Request.RequestID, RequestStatus.[DCPM Project Status] FROM RequestStatus"
                        " INNER JOIN Request ON RequestStatus.StatusID = Request.StatusID; "
                    ColumnWidths ="0;1440"
                    EventProcPrefix ="DCPM_Project_Status"
                    BaseInfo ="\"SELECT Request.RequestID, RequestStatus.[DCPM Project Status] FROM RequestStat"
                        "us INNER JOIN Request ON RequestStatus.StatusID = Request.StatusID; \";\"Request"
                        "Status\";\"Request\";\"\""
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638
                    AllowValueListEdits =0

                    LayoutCachedLeft =2310
                    LayoutCachedTop =4080
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =4395
                    RowStart =8
                    RowEnd =8
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =4080
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label6"
                            Caption ="DCPM Project Status"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =4080
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =4395
                            RowStart =8
                            RowEnd =8
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2310
                    Top =3585
                    Width =1950
                    Height =315
                    TabIndex =7
                    BorderColor =10921638
                    Name ="DCPMUtilzation"
                    ControlSource ="UtilizationPercent"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2310
                    LayoutCachedTop =3585
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =3900
                    RowStart =7
                    RowEnd =7
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =2
                    ForeTint =100.0
                    ForeShade =50.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =3585
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label28"
                            Caption ="Util %"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =3585
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =3900
                            RowStart =7
                            RowEnd =7
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    Locked = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    ColumnCount =2
                    Left =2310
                    Top =1110
                    Width =1950
                    Height =315
                    ColumnWidth =2700
                    TabIndex =1
                    BorderColor =10921638
                    ForeColor =4210752
                    ColumnInfo ="\"\";\"\";\"\";\"\";\"10\";\"510\""
                    Name ="Customer Name"
                    ControlSource ="RequestID"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT Request.RequestID, CustomersTable.CustomerName FROM CustomersTable INNER "
                        "JOIN Request ON CustomersTable.CustomerID = Request.CustomerID; "
                    ColumnWidths ="0;1440"
                    EventProcPrefix ="Customer_Name"
                    BaseInfo ="\"SELECT Request.RequestID, CustomersTable.CustomerName FROM CustomersTable INNE"
                        "R JOIN Request ON CustomersTable.CustomerID = Request.CustomerID; \";\"Customers"
                        "Table\";\"Request\";\"\""
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2310
                    LayoutCachedTop =1110
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =1425
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =0
                    ForeTint =75.0
                    ForeShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =1110
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label2"
                            Caption ="Customer Name"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =1110
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =1425
                            RowStart =2
                            RowEnd =2
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    Locked = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    ColumnCount =2
                    Left =2310
                    Top =1605
                    Width =1950
                    Height =315
                    TabIndex =2
                    BorderColor =10921638
                    ForeColor =4210752
                    ColumnInfo ="\"\";\"\";\"\";\"\";\"10\";\"510\""
                    Name ="Project ID (PID)PID"
                    ControlSource ="RequestID"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT Request.RequestID, Request.ProjectID FROM Request; "
                    ColumnWidths ="0;1440"
                    EventProcPrefix ="Project_ID__PID_PID"
                    BaseInfo ="\"SELECT Request.RequestID, Request.ProjectID FROM Request; \";\"Request\";\"\";"
                        "\"RequestID\";\"ProjectID\";\"PrimaryKey\""
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2310
                    LayoutCachedTop =1605
                    LayoutCachedWidth =4260
                    LayoutCachedHeight =1920
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =0
                    ForeTint =75.0
                    ForeShade =100.0
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =1
                            Left =300
                            Top =1605
                            Width =1950
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Label21"
                            Caption ="PID"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =300
                            LayoutCachedTop =1605
                            LayoutCachedWidth =2250
                            LayoutCachedHeight =1920
                            RowStart =3
                            RowEnd =3
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
            End
        End
    End
End
