Version =20
VersionRequired =20
PublishOption =1
    RecordSelectors = NotDefault
    AutoCenter = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    FilterOn = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =9540
    DatasheetFontHeight =11
    ItemSuffix =110
    Left =645
    Top =5775
    Right =12150
    Bottom =9600
    DatasheetGridlinesColor =16316664
        0x5424fde91040e440
    End
    RecordSource ="SELECT [ROI-Tracking].[Investment ID], [ROI-Tracking].[Account Name], [ROI-Track"
        "ing].[AreaRegion], [ROI-Tracking].[OppertunityNameDescription], [ROI-Tracking].["
        "Investment Amount $], [ROI-Tracking].[% DC & C], [ROI-Tracking].[%Advisory], [RO"
        "I-Tracking].[CSX Contact], [ROI-Tracking].[Project ID], [ROI-Tracking].[RequestI"
        "D], [ROI-Tracking].[Funds Used] FROM [ROI-Tracking]; "
    Caption ="ROI-Tracking subform"
    DatasheetFontName ="Calibri"
    AllowPivotTableView =0
    AllowPivotChartView =0
    AllowPivotChartView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =240
            GridlineColor =12632256
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =0
            BackColor =13421772
            Name ="FormHeader"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =2
            BackTint =20.0
        End
            Height =2220
            Name ="Detail"
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    Visible = NotDefault
                    OverlapFlags =93
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2490
                    Top =30
                    Width =2520
                    Height =14
                    ColumnWidth =1440
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Investment ID"
                    ControlSource ="Investment ID"
                    EventProcPrefix ="Investment_ID"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =10921638

                    LayoutCachedLeft =2490
                    LayoutCachedTop =30
                    LayoutCachedWidth =5010
                    LayoutCachedHeight =44
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =30
                            Top =30
                            Width =2460
                            Height =14
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Investment ID_Label"
                            Caption ="Investment ID"
                            EventProcPrefix ="Investment_ID_Label"
                            GroupTable =1
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineColor =10921638
                            LayoutCachedLeft =30
                            LayoutCachedTop =30
                            LayoutCachedWidth =2490
                            LayoutCachedHeight =44
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2490
                    Top =105
                    Width =2520
                    Height =330
                    ColumnWidth =3000
                    TabIndex =3
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Account Name"
                    ControlSource ="Account Name"
                    EventProcPrefix ="Account_Name"
                    GroupTable =1
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2490
                    LayoutCachedTop =105
                    LayoutCachedWidth =5010
                    LayoutCachedHeight =435
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =3
                            Left =30
                            Top =105
                            Width =2460
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Account Name_Label"
                            Caption ="Account Name"
                            EventProcPrefix ="Account_Name_Label"
                            GroupTable =1
                            LeftPadding =0
                            RightPadding =0
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =30
                            LayoutCachedTop =105
                            LayoutCachedWidth =2490
                            LayoutCachedHeight =435
                            RowStart =3
                            RowEnd =3
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    LimitToList = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    ColumnCount =2
                    Left =6480
                    Top =615
                    Width =2790
                    Height =330
                    ColumnWidth =3000
                    TabIndex =6
                    BorderColor =10921638
                    Name ="AreaRegion"
                    ControlSource ="AreaRegion"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT [ID], [Area] FROM [Area Investment Sign Off list] ORDER BY [Area]; "
                    ColumnWidths ="0;1440"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638
                    AllowValueListEdits =0

                    LayoutCachedLeft =6480
                    LayoutCachedTop =615
                    LayoutCachedWidth =9270
                    LayoutCachedHeight =945
                    RowStart =4
                    RowEnd =4
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =3
                            Left =5040
                            Top =615
                            Width =1380
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="AreaRegion_Label"
                            Caption ="AreaRegion"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =5040
                            LayoutCachedTop =615
                            LayoutCachedWidth =6420
                            LayoutCachedHeight =945
                            RowStart =4
                            RowEnd =4
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    Visible = NotDefault
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =93
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2490
                    Top =60
                    Width =2520
                    Height =15
                    ColumnWidth =3000
                    TabIndex =2
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="OppertunityNameDescription"
                    ControlSource ="OppertunityNameDescription"
                    DefaultValue ="\"D10 Workshop\""
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =10921638

                    LayoutCachedLeft =2490
                    LayoutCachedTop =60
                    LayoutCachedWidth =5010
                    LayoutCachedHeight =75
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =30
                            Top =60
                            Width =2460
                            Height =15
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="OppertunityNameDescription_Label"
                            Caption ="OppertunityNameDescription"
                            GroupTable =1
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineColor =10921638
                            LayoutCachedLeft =30
                            LayoutCachedTop =60
                            LayoutCachedWidth =2490
                            LayoutCachedHeight =75
                            RowStart =2
                            RowEnd =2
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2490
                    Top =615
                    Width =2520
                    Height =330
                    ColumnWidth =3000
                    TabIndex =5
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Investment Amount $"
                    ControlSource ="Investment Amount $"
                    Format ="$#,##0.00;($#,##0.00)"
                    EventProcPrefix ="Investment_Amount__"
                    GroupTable =1
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2490
                    LayoutCachedTop =615
                    LayoutCachedWidth =5010
                    LayoutCachedHeight =945
                    RowStart =4
                    RowEnd =4
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                    CurrencySymbol ="$"
                    ColLCID =1033
                            OverlapFlags =85
                            TextAlign =3
                            Left =30
                            Top =615
                            Width =2460
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Investment Amount $_Label"
                            Caption ="Investment Amount $"
                            EventProcPrefix ="Investment_Amount___Label"
                            GroupTable =1
                            LeftPadding =0
                            RightPadding =0
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =30
                            LayoutCachedTop =615
                            LayoutCachedWidth =2490
                            LayoutCachedHeight =945
                            RowStart =4
                            RowEnd =4
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    DecimalPlaces =0
                    OverlapFlags =85
                    AccessKey =32
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2490
                    Top =1125
                    Width =2520
                    Height =330
                    ColumnWidth =1200
                    TabIndex =7
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="% DC & C"
                    ControlSource ="% DC & C"
                    Format ="Percent"
                    DefaultValue ="0.8"
                    EventProcPrefix ="Ctl__DC___C"
                    UnicodeAccessKey =32
                    GroupTable =1
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2490
                    LayoutCachedTop =1125
                    LayoutCachedWidth =5010
                    LayoutCachedHeight =1455
                    RowStart =5
                    RowEnd =5
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =3
                            Left =30
                            Top =1125
                            Width =2460
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="% DC & C_Label"
                            Caption ="% DC & C"
                            EventProcPrefix ="Ctl__DC___C_Label"
                            GroupTable =1
                            LeftPadding =0
                            RightPadding =0
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =30
                            LayoutCachedTop =1125
                            LayoutCachedWidth =2490
                            LayoutCachedHeight =1455
                            RowStart =5
                            RowEnd =5
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    DecimalPlaces =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2490
                    Top =1635
                    Width =2520
                    Height =330
                    ColumnWidth =1200
                    TabIndex =9
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="%Advisory"
                    ControlSource ="%Advisory"
                    Format ="Percent"
                    DefaultValue ="0.2"
                    EventProcPrefix ="Ctl_Advisory"
                    GroupTable =1
                    LeftPadding =0
                    RightPadding =0
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =2490
                    LayoutCachedTop =1635
                    LayoutCachedWidth =5010
                    LayoutCachedHeight =1965
                    RowStart =6
                    RowEnd =6
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =3
                            Left =30
                            Top =1635
                            Width =2460
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="%Advisory_Label"
                            Caption ="%Advisory"
                            EventProcPrefix ="Ctl_Advisory_Label"
                            GroupTable =1
                            LeftPadding =0
                            RightPadding =0
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =30
                            LayoutCachedTop =1635
                            LayoutCachedWidth =2490
                            LayoutCachedHeight =1965
                            RowStart =6
                            RowEnd =6
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    LimitToList = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    ColumnCount =2
                    Left =6480
                    Top =1635
                    Width =2790
                    Height =330
                    ColumnWidth =3000
                    TabIndex =10
                    BorderColor =10921638
                    Name ="CSX Contact"
                    ControlSource ="CSX Contact"
                    RowSourceType ="Table/Query"
                    RowSource ="SELECT [ID], [Contact Name] FROM [Contacts Extended] ORDER BY [Contact Name]; "
                    ColumnWidths ="0;1440"
                    EventProcPrefix ="CSX_Contact"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638
                    ListItemsEditForm ="Contact Details"

                    LayoutCachedLeft =6480
                    LayoutCachedTop =1635
                    LayoutCachedWidth =9270
                    LayoutCachedHeight =1965
                    RowStart =6
                    RowEnd =6
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =3
                            Left =5040
                            Top =1635
                            Width =1380
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="CSX Contact_Label"
                            Caption ="CSX Contact"
                            EventProcPrefix ="CSX_Contact_Label"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =5040
                            LayoutCachedTop =1635
                            LayoutCachedWidth =6420
                            LayoutCachedHeight =1965
                            RowStart =6
                            RowEnd =6
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =6480
                    Top =105
                    Width =2790
                    Height =330
                    ColumnWidth =3000
                    TabIndex =4
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Project ID"
                    ControlSource ="Project ID"
                    EventProcPrefix ="Project_ID"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =6480
                    LayoutCachedTop =105
                    LayoutCachedWidth =9270
                    LayoutCachedHeight =435
                    RowStart =3
                    RowEnd =3
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                            OverlapFlags =85
                            TextAlign =3
                            Left =5040
                            Top =105
                            Width =1380
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Project ID_Label"
                            Caption ="Project ID"
                            EventProcPrefix ="Project_ID_Label"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =5040
                            LayoutCachedTop =105
                            LayoutCachedWidth =6420
                            LayoutCachedHeight =435
                            RowStart =3
                            RowEnd =3
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    Visible = NotDefault
                    OverlapFlags =87
                    TextAlign =1
                    IMESentenceMode =3
                    Left =2490
                    Top =45
                    Width =2520
                    Height =15
                    ColumnWidth =1530
                    TabIndex =1
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="RequestID"
                    ControlSource ="RequestID"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =10921638

                    LayoutCachedLeft =2490
                    LayoutCachedTop =45
                    LayoutCachedWidth =5010
                    LayoutCachedHeight =60
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =30
                            Top =45
                            Width =2460
                            Height =15
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="RequestID_Label"
                            Caption ="RequestID"
                            GroupTable =1
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineColor =10921638
                            LayoutCachedLeft =30
                            LayoutCachedTop =45
                            LayoutCachedWidth =2490
                            LayoutCachedHeight =60
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =6480
                    Top =1125
                    Width =2790
                    Height =330
                    ColumnWidth =3000
                    TabIndex =8
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Funds Used"
                    ControlSource ="Funds Used"
                    Format ="$#,##0.00;($#,##0.00)"
                    EventProcPrefix ="Funds_Used"
                    GroupTable =1
                    BottomPadding =150
                    GridlineColor =10921638

                    LayoutCachedLeft =6480
                    LayoutCachedTop =1125
                    LayoutCachedWidth =9270
                    LayoutCachedHeight =1455
                    RowStart =5
                    RowEnd =5
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                    CurrencySymbol ="$"
                    ColLCID =1033
                            OverlapFlags =85
                            TextAlign =3
                            Left =5040
                            Top =1125
                            Width =1380
                            Height =330
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Funds Used_Label"
                            Caption ="Funds Used"
                            EventProcPrefix ="Funds_Used_Label"
                            GroupTable =1
                            BottomPadding =150
                            GridlineColor =10921638
                            LayoutCachedLeft =5040
                            LayoutCachedTop =1125
                            LayoutCachedWidth =6420
                            LayoutCachedHeight =1455
                            RowStart =5
                            RowEnd =5
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            GroupTable =1
                        End
                    End
                End
                    Left =6480
                    Top =30
                    Width =2790
                    Height =14
                    Name ="EmptyCell54"
                    GroupTable =1
                    TopPadding =0
                    BottomPadding =0
                    GridlineColor =10921638
                    LayoutCachedLeft =6480
                    LayoutCachedTop =30
                    LayoutCachedWidth =9270
                    LayoutCachedHeight =44
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
                    Left =6480
                    Top =60
                    Width =2790
                    Height =15
                    Name ="EmptyCell55"
                    GroupTable =1
                    TopPadding =0
                    BottomPadding =0
                    GridlineColor =10921638
                    LayoutCachedLeft =6480
                    LayoutCachedTop =60
                    LayoutCachedWidth =9270
                    LayoutCachedHeight =75
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
                    Left =5040
                    Top =30
                    Width =1380
                    Height =14
                    Name ="EmptyCell65"
                    GroupTable =1
                    TopPadding =0
                    BottomPadding =0
                    GridlineColor =10921638
                    LayoutCachedLeft =5040
                    LayoutCachedTop =30
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =44
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                    Left =5040
                    Top =60
                    Width =1380
                    Height =15
                    Name ="EmptyCell66"
                    GroupTable =1
                    TopPadding =0
                    BottomPadding =0
                    GridlineColor =10921638
                    LayoutCachedLeft =5040
                    LayoutCachedTop =60
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =75
                    RowStart =2
                    RowEnd =2
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                    Left =5040
                    Top =45
                    Width =1380
                    Height =15
                    Name ="EmptyCell82"
                    GroupTable =1
                    TopPadding =0
                    BottomPadding =0
                    GridlineColor =10921638
                    LayoutCachedLeft =5040
                    LayoutCachedTop =45
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =60
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                    Left =6480
                    Top =45
                    Width =2790
                    Height =15
                    Name ="EmptyCell83"
                    GroupTable =1
                    TopPadding =0
                    BottomPadding =0
                    GridlineColor =10921638
                    LayoutCachedLeft =6480
                    LayoutCachedTop =45
                    LayoutCachedWidth =9270
                    LayoutCachedHeight =60
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
            End
        End
            Height =0
            Name ="FormFooter"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
