Version =20
VersionRequired =20
PublishOption =1
    PopUp = NotDefault
    Modal = NotDefault
    RecordSelectors = NotDefault
    AutoCenter = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    ViewsAllowed =1
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =6825
    DatasheetFontHeight =11
    ItemSuffix =120
    Left =4050
    Top =2415
    Right =19650
    Bottom =14715
    DatasheetGridlinesColor =14806254
    Filter ="[RequestID]=1592"
        0x4abcdadd8c2ee440
    End
    RecordSource ="SELECT ROITracking.*, * FROM ROITracking; "
    Caption ="ROITracking"
    DatasheetFontName ="Calibri"
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    AllowDatasheetView =0
    AllowPivotTableView =0
    AllowPivotChartView =0
    AllowPivotChartView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            AddColon = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            BorderLineStyle =0
            BorderThemeColorIndex =1
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            BorderShade =65.0
            ShowPageHeaderAndPageFooter =1
        End
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =3
            BackThemeColorIndex =1
            BackShade =85.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =2
            BorderTint =60.0
            HoverThemeColorIndex =1
            PressedThemeColorIndex =1
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =240
            GridlineColor =12632256
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =690
            BackColor =15849926
            Name ="FormHeader"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =2
            BackTint =20.0
                    OverlapFlags =85
                    Left =60
                    Top =60
                    Width =2844
                    Height =540
                    FontSize =20
                    BorderColor =8355711
                    ForeColor =8355711
                    Name ="Label30"
                    Caption ="ROITracking"
                    GridlineColor =10921638
                    LayoutCachedLeft =60
                    LayoutCachedTop =60
                    LayoutCachedWidth =2904
                    LayoutCachedHeight =600
                End
                    Visible = NotDefault
                    OverlapFlags =93
                    TextAlign =1
                    IMESentenceMode =3
                    Left =4635
                    Top =60
                    Width =1545
                    Height =315
                    ColumnWidth =1440
                    ColumnOrder =0
                    FontSize =8
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Investment ID"
                    ControlSource ="Investment ID"
                    EventProcPrefix ="Investment_ID"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =10921638

                    LayoutCachedLeft =4635
                    LayoutCachedTop =60
                    LayoutCachedWidth =6180
                    LayoutCachedHeight =375
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =3030
                            Top =60
                            Width =1605
                            Height =315
                            FontSize =8
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Investment ID_Label"
                            Caption ="Investment ID"
                            EventProcPrefix ="Investment_ID_Label"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineColor =10921638
                            LayoutCachedLeft =3030
                            LayoutCachedTop =60
                            LayoutCachedWidth =4635
                            LayoutCachedHeight =375
                            LayoutGroup =1
                            GroupTable =2
                        End
                    End
                End
                    Visible = NotDefault
                    OverlapFlags =95
                    TextAlign =1
                    IMESentenceMode =3
                    Left =4635
                    Top =375
                    Width =1545
                    Height =315
                    ColumnWidth =1605
                    ColumnOrder =1
                    FontSize =8
                    TabIndex =1
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="RequestID"
                    ControlSource ="RequestID"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =10921638

                    LayoutCachedLeft =4635
                    LayoutCachedTop =375
                    LayoutCachedWidth =6180
                    LayoutCachedHeight =690
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =3030
                            Top =375
                            Width =1605
                            Height =315
                            FontSize =8
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="RequestID_Label"
                            Caption ="RequestID"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineColor =10921638
                            LayoutCachedLeft =3030
                            LayoutCachedTop =375
                            LayoutCachedWidth =4635
                            LayoutCachedHeight =690
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =1
                            GroupTable =2
                        End
                    End
                End
                    Visible = NotDefault
                    OverlapFlags =87
                    TextAlign =1
                    IMESentenceMode =3
                    Left =4635
                    Top =690
                    Width =1545
                    Height =0
                    ColumnWidth =1605
                    ColumnOrder =2
                    FontSize =8
                    TabIndex =2
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="ROITracking_ReturnID"
                    ControlSource ="ROITracking_ReturnID"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =10921638

                    LayoutCachedLeft =4635
                    LayoutCachedTop =690
                    LayoutCachedWidth =6180
                    LayoutCachedHeight =690
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                            Visible = NotDefault
                            OverlapFlags =85
                            TextAlign =1
                            Left =3030
                            Top =690
                            Width =1605
                            Height =0
                            FontSize =8
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="ROITracking_ReturnID_Label"
                            Caption ="ROITracking_ReturnID"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            GridlineColor =10921638
                            LayoutCachedLeft =3030
                            LayoutCachedTop =690
                            LayoutCachedWidth =4635
                            LayoutCachedHeight =690
                            RowStart =2
                            RowEnd =2
                            LayoutGroup =1
                            GroupTable =2
                        End
                    End
                End
            End
        End
            CanGrow = NotDefault
            Height =4980
            Name ="Detail"
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    OverlapFlags =85
                    TextFontFamily =18
                    Left =135
                    Top =150
                    Width =6690
                    Height =4545
                    Name ="TabCtl57"
                    FontName ="Cambria"
                    GridlineColor =10921638

                    LayoutCachedLeft =135
                    LayoutCachedTop =150
                    LayoutCachedWidth =6825
                    LayoutCachedHeight =4695
                    BackColor =14277081
                    BorderColor =13995605
                    HoverForeColor =4210752
                    PressedForeColor =4210752
                    ForeColor =4210752
                            OverlapFlags =87
                            Left =210
                            Top =660
                            Width =6540
                            Height =3960
                            BorderColor =10921638
                            Name ="Investment Info"
                            EventProcPrefix ="Investment_Info"
                            GridlineColor =10921638
                            LayoutCachedLeft =210
                            LayoutCachedTop =660
                            LayoutCachedWidth =6750
                            LayoutCachedHeight =4620
                            WebImagePaddingLeft =2
                            WebImagePaddingTop =2
                            WebImagePaddingRight =2
                            WebImagePaddingBottom =2
                                    EnterKeyBehavior = NotDefault
                                    ScrollBars =2
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    Left =2430
                                    Top =3690
                                    Width =4140
                                    Height =570
                                    BorderColor =10921638
                                    ForeColor =4210752
                                    Name ="Project ID"
                                    ControlSource ="Project ID"
                                    EventProcPrefix ="Project_ID"
                                    GroupTable =5
                                    GridlineColor =10921638

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =3690
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =4260
                                    RowStart =7
                                    RowEnd =7
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =3690
                                            Width =2130
                                            Height =570
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="Project ID_Label"
                                            Caption ="Project ID"
                                            EventProcPrefix ="Project_ID_Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =3690
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =4260
                                            RowStart =7
                                            RowEnd =7
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                                    LimitToList = NotDefault
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    ColumnCount =2
                                    Left =2430
                                    Top =3315
                                    Width =4140
                                    Height =315
                                    BorderColor =10921638
                                    ForeColor =4138256
                                    ColumnInfo ="\"\";\"\";\"\";\"\";\"10\";\"0\""
                                    Name ="CSX Contact"
                                    ControlSource ="CSX Contact"
                                    RowSourceType ="Table/Query"
                                    RowSource ="SELECT [ID], [Contact Name] FROM [Contacts Extended] ORDER BY [Contact Name]; "
                                    ColumnWidths ="0;1440"
                                    EventProcPrefix ="CSX_Contact"
                                    GroupTable =5
                                    GridlineColor =10921638
                                    ListItemsEditForm ="ContactDetails"

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =3315
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =3630
                                    RowStart =6
                                    RowEnd =6
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =3315
                                            Width =2130
                                            Height =315
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="CSX Contact_Label"
                                            Caption ="CSX Contact"
                                            EventProcPrefix ="CSX_Contact_Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =3315
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =3630
                                            RowStart =6
                                            RowEnd =6
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                                    DecimalPlaces =0
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    Left =2430
                                    Top =2940
                                    Width =4140
                                    Height =315
                                    BorderColor =10921638
                                    ForeColor =4210752
                                    Name ="%Advisory"
                                    ControlSource ="%Advisory"
                                    Format ="Percent"
                                    EventProcPrefix ="Ctl_Advisory"
                                    GroupTable =5
                                    GridlineColor =10921638

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =2940
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =3255
                                    RowStart =5
                                    RowEnd =5
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =2940
                                            Width =2130
                                            Height =315
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="%Advisory_Label"
                                            Caption ="%Advisory"
                                            EventProcPrefix ="Ctl_Advisory_Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =2940
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =3255
                                            RowStart =5
                                            RowEnd =5
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                                    DecimalPlaces =0
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    Left =2430
                                    Top =2565
                                    Width =4140
                                    Height =315
                                    BorderColor =10921638
                                    ForeColor =4210752
                                    Name ="% DC & C"
                                    ControlSource ="% DC & C"
                                    Format ="Percent"
                                    EventProcPrefix ="Ctl__DC___C"
                                    GroupTable =5
                                    GridlineColor =10921638

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =2565
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =2880
                                    RowStart =4
                                    RowEnd =4
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =2565
                                            Width =2130
                                            Height =315
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="% DC & C_Label"
                                            Caption ="% DCC"
                                            EventProcPrefix ="Ctl__DC___C_Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =2565
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =2880
                                            RowStart =4
                                            RowEnd =4
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    Left =2430
                                    Top =2190
                                    Width =4140
                                    Height =315
                                    BorderColor =10921638
                                    ForeColor =4210752
                                    Name ="Investment Amount $"
                                    ControlSource ="Investment Amount $"
                                    Format ="$#,##0.00;($#,##0.00)"
                                    EventProcPrefix ="Investment_Amount__"
                                    GroupTable =5
                                    GridlineColor =10921638

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =2190
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =2505
                                    RowStart =3
                                    RowEnd =3
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                    CurrencySymbol ="$"
                                    ColLCID =1033
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =2190
                                            Width =2130
                                            Height =315
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="Investment Amount $_Label"
                                            Caption ="Investment $"
                                            EventProcPrefix ="Investment_Amount___Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =2190
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =2505
                                            RowStart =3
                                            RowEnd =3
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                                    EnterKeyBehavior = NotDefault
                                    ScrollBars =2
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    Left =2430
                                    Top =1560
                                    Width =4140
                                    Height =570
                                    BorderColor =10921638
                                    ForeColor =4210752
                                    Name ="Oppertunity Name/Description"
                                    ControlSource ="Oppertunity Name/Description"
                                    EventProcPrefix ="Oppertunity_Name_Description"
                                    GroupTable =5
                                    GridlineColor =10921638

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =1560
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =2130
                                    RowStart =2
                                    RowEnd =2
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =1560
                                            Width =2130
                                            Height =570
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="Oppertunity Name/Description_Label"
                                            Caption ="Oppertunity Name/Description"
                                            EventProcPrefix ="Oppertunity_Name_Description_Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =1560
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =2130
                                            RowStart =2
                                            RowEnd =2
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                                    LimitToList = NotDefault
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    ColumnCount =2
                                    Left =2430
                                    Top =1185
                                    Width =4140
                                    Height =315
                                    BorderColor =10921638
                                    ForeColor =4138256
                                    ColumnInfo ="\"\";\"\";\"\";\"\";\"10\";\"510\""
                                    Name ="Area/Region"
                                    ControlSource ="Area/Region"
                                    RowSourceType ="Table/Query"
                                    RowSource ="SELECT [InvestmentID], [Area] FROM [Area Investment Sign Off list] ORDER BY [Are"
                                        "a]; "
                                    ColumnWidths ="0;1440"
                                    EventProcPrefix ="Area_Region"
                                    GroupTable =5
                                    GridlineColor =10921638
                                    AllowValueListEdits =0

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =1185
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =1500
                                    RowStart =1
                                    RowEnd =1
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =1185
                                            Width =2130
                                            Height =315
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="Area/Region_Label"
                                            Caption ="Area/Region"
                                            EventProcPrefix ="Area_Region_Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =1185
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =1500
                                            RowStart =1
                                            RowEnd =1
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                                    EnterKeyBehavior = NotDefault
                                    ScrollBars =2
                                    OverlapFlags =215
                                    TextAlign =1
                                    IMESentenceMode =3
                                    Left =2430
                                    Top =765
                                    Width =4140
                                    Height =360
                                    BorderColor =10921638
                                    ForeColor =4210752
                                    Name ="Account Name"
                                    ControlSource ="Account Name"
                                    EventProcPrefix ="Account_Name"
                                    GroupTable =5
                                    GridlineColor =10921638

                                    LayoutCachedLeft =2430
                                    LayoutCachedTop =765
                                    LayoutCachedWidth =6570
                                    LayoutCachedHeight =1125
                                    ColumnStart =1
                                    ColumnEnd =1
                                    LayoutGroup =2
                                    GroupTable =5
                                            OverlapFlags =215
                                            TextAlign =3
                                            Left =240
                                            Top =765
                                            Width =2130
                                            Height =360
                                            BorderColor =8355711
                                            ForeColor =8355711
                                            Name ="Account Name_Label"
                                            Caption ="Account Name"
                                            EventProcPrefix ="Account_Name_Label"
                                            GroupTable =5
                                            GridlineColor =10921638
                                            LayoutCachedLeft =240
                                            LayoutCachedTop =765
                                            LayoutCachedWidth =2370
                                            LayoutCachedHeight =1125
                                            LayoutGroup =2
                                            GroupTable =5
                                        End
                                    End
                                End
                            End
                        End
                            OverlapFlags =247
                            Left =210
                            Top =660
                            Width =6540
                            Height =3960
                            BorderColor =10921638
                            Name ="Return Info"
                            EventProcPrefix ="Return_Info"
                            GridlineColor =10921638
                            LayoutCachedLeft =210
                            LayoutCachedTop =660
                            LayoutCachedWidth =6750
                            LayoutCachedHeight =4620
                            WebImagePaddingLeft =2
                            WebImagePaddingTop =2
                            WebImagePaddingRight =2
                            WebImagePaddingBottom =2
                                    OverlapFlags =247
                                    Left =540
                                    Top =720
                                    Width =6135
                                    Height =3360
                                    BorderColor =10921638
                                    Name ="Return subform"
                                    SourceObject ="Form.Return subform"
                                    LinkChildFields ="RequestID"
                                    LinkMasterFields ="RequestID"
                                    EventProcPrefix ="Return_subform"
                                    GridlineColor =10921638

                                    LayoutCachedLeft =540
                                    LayoutCachedTop =720
                                    LayoutCachedWidth =6675
                                    LayoutCachedHeight =4080
                                End
                                    Left =675
                                    Top =1020
                                    Name ="EmptyCell118"
                                    GroupTable =6
                                    GridlineColor =10921638
                                    LayoutCachedLeft =675
                                    LayoutCachedTop =1020
                                    LayoutCachedWidth =2115
                                    LayoutCachedHeight =1260
                                    LayoutGroup =3
                                    GroupTable =6
                                End
                            End
                        End
                    End
                End
            End
        End
            Height =0
            Name ="FormFooter"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
